### ISSUE TITLE
Incorrect weights for TRAILMAP_MS ?

### ISSUE THREAD

**Issue by C-Achard** [AdaptiveMotorControlLab/CellSeg3d#18]
After downloading the TRAILMAP_MS weights for inference, I get the following :
Error(s) in loading state_dict for TRAILMAP_MS:
        Missing key(s) in state_dict: 
(long list of missing keys...)
Unexpected key(s) in state_dict:
(long list of unexpected keys...)

Could it be that they are not the correct ones ? How easily can we update the weights @  http://deeplabcut.rowland.harvard.edu/cellseg3dmodels ?

**Comment by MMathisLab** [comment]
these are the best mesoSPIM trained weights for this model, per @vidalmaxime

**Comment by C-Achard** [comment]
I just think they are paired to the wrong model, so it causes an error in the plugin.

**Comment by MMathisLab** [comment]
yes, so to clarify: 😎

There are 4 models (+ unet, which isn't supported actually?): 


<img width="343" alt="Screen Shot 2022-07-14 at 4 56 23 PM" src="https://user-images.githubusercontent.com/28102185/179013015-cbc8f7b0-b7b2-4603-a42e-3865052e580e.png">

and TRAILMAP --> trailmap-pytorch
TRAILMAP_MS --> trailmap-ms trained on mesospim data

**Comment by C-Achard** [comment]
@MMathisLab The Unet folder is for what is currently called TRAILMAP_MS, it's simply code from https://github.com/wolny/pytorch-3dunet Maxime used to re-create TRAILMAP in a more robust way

**Comment by C-Achard** [comment]
Naming issues have been addressed in #19, see 34da28b.

However, the weights file for TRAILMAP_PyTorch on the server is still incorrect, I can provide one when appropriate so we can update it on the server.
