### ISSUE TITLE
Inference with VNet not running - RuntimeError in aborted thread

### ISSUE THREAD

**Issue by thecobb** [AdaptiveMotorControlLab/CellSeg3d#20]
I'm getting an error when trying to use VNet with a folder than has the tiff files corresponding to a whole brain scan of a cleared brain from a Lavision Ultramiscrope II stitched together using Imaris and resaved as an image sequence using FIJI to shorten the filename. I've also tried other models and have gotten different issues but am less concerned about resolving them since having VNet working would be sufficient. 

The system I am using is a Windows 10 workstation with an AMD 5950x and Nvidia 3090TI with 128GB RAM and 2 TB SSD with 1 TB available. In the error below, it is using the CPU implementation but I have encountered the same error using an implementation where I had the GPU-enabled Pytorch installed. 

The output of the terminal in text is pasted below. Below that are screenshots of the settings and terminal output itself. 

(cellseg) C:\Users\free_\Documents\GitHub\CellSeg3d>napari
C:\Users\free_
C:/irfp_rename
Starting...
********************
Using cpu device
Using torch :
1.11.0+cpu
Downloading the model from the M.W. Mathis Lab server http://deeplabcut.rowland.harvard.edu/cellseg3dmodels/VNet.tar.gz....
168828928B [00:15, 10931902.90B/s]
OS is Windows
Worker started at 14:27:39
Saving results to : C:/results
Worker is running...
TIFFReadDirectory: Warning, Unknown field with tag 50838 (0xc696) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 50839 (0xc697) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 50838 (0xc696) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 50839 (0xc697) encountered.
C:\Users\free_\Anaconda3\envs\cellseg\lib\site-packages\superqt\utils\_qthreading.py:183: RuntimeWarning: RuntimeError in aborted thread: Can't downcast to a specialization of MetaDataObject!

Screenshots of the terminal output and Cellseg settings below. I screenshotted the terminal after a stop request because in the past the program has gotten stuck after the error related to the aborted thread.

![cellseg_terminal](https://user-images.githubusercontent.com/17283036/178336462-bebf4009-03d3-46dc-9e44-2d38a03a5aee.png)
![cellseg_settings](https://user-images.githubusercontent.com/17283036/178336463-07171ed3-5cc0-474e-a889-b5c9e1804cf2.png)

**Comment by thecobb** [comment]
I'm also getting the same error when trying to run inference on an M1 Max Macbook pro. with the VNet model. Screenshots of terminal output and settings below. 

<img width="1512" alt="Screen Shot 2022-07-12 at 7 22 05 PM" src="https://user-images.githubusercontent.com/17283036/178614987-1eb6581e-cfd9-4d96-99cc-cfa6933e6eed.png">
<img width="1512" alt="Screen Shot 2022-07-12 at 7 21 53 PM" src="https://user-images.githubusercontent.com/17283036/178614988-90ae37e4-6005-401d-b65c-e4a3eb74ba68.png">

**Comment by C-Achard** [comment]
Hello @thecobb, thank you for reporting those issues !

I'll look into the .tiff loading issues as you mentioned in #21, otherwise I'm intrigued as to why it considers your data to be 2D.

Just to confirm regarding the images being "stitched together using Imaris and resaved as an image sequence using FIJI to shorten the filename" : are you running inference on a folder of several 2D images, or a folder with a single/several 3D image(s) ?

Looking at the docs, I realise it might have been ambiguous, only inference on a folder of 3D images is supported currently; loading a stack of 2D images is not supported for inference and training, unlike for review or cropping. I've updated the docs to reflect this, sorry if it was unclear.

If you'd find it useful to have the possibility to run inference on a 2D stack, please let me know, I can add this to the feature request list and work on implementing it.

(on a side note, if you are using a single 3D image, running inference on such a large volume might be problematic without using window inference, it would require a lot of memory to run 3D UNets on such a large image. If you do have access to a single 3D file, maybe try using window inference, or cropping a smaller piece of the volume, such as a 128 or 256 wide cube, and then running inference on it ? On Windows you could also monitor your RAM/VRAM usage with the Performance tab of the Task Manager, to see if memory is an issue. Or any similar monitoring utility if you're on another OS.)

**Comment by thecobb** [comment]
Hi C-Achard,

I was using a folder of 2d images that comprised a full z-stack. I have switched to loading a folder that has only one 3d multi-page tiff. By using the 3D tif I'm getting a new error (which I get regardless of model selected) and am including a screencast [https://capture.dropbox.com/HSDHuEE3IS65lk6q](Dropbox Capture Screencast) as well as screenshots below. I get this error regardless if I use Vnet or SegResNet. I've also used the window inference, I had previously been using it but purposely left it off in examples above since it wasn't getting to the point where either the RAM or GPU RAM were being loaded onto. It would be useful to be able to run inference on a 2D stack but I'm able to concatenate the images into a 3D tiff file so it's not an issue to modify my data to use with the inference function. Looking at my GPU and RAM usage, neither has increased since clicking start within the inference menu.

Now the error is as follows: 

`C:\Users\free_\Anaconda3\envs\cellseg\lib\site-packages\superqt\utils\_qthreading.py:183: RuntimeWarning: RuntimeError in aborted thread: Can't downcast to a specialization of MetaDataObject!`

The terminal output is as follows:

(cellseg) C:\Users\free_>napari
C:\Users\free_
C:/irfp_multi
Starting...
********************
Using cuda device
Using torch :
1.11.0+cu113
Downloading the model from the M.W. Mathis Lab server http://deeplabcut.rowland.harvard.edu/cellseg3dmodels/TRAILMAP.tar.gz....
60538880B [00:05, 10415713.72B/s]
OS is Windows
Worker started at 13:47:15
Saving results to : C:/results
Worker is running...
TIFFReadDirectory: Warning, Unknown field with tag 50838 (0xc696) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 50839 (0xc697) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 50838 (0xc696) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 50839 (0xc697) encountered.
C:\Users\free_\Anaconda3\envs\cellseg\lib\site-packages\superqt\utils\_qthreading.py:183: RuntimeWarning: RuntimeError in aborted thread: Can't downcast to a specialization of MetaDataObject!


And screenshots that might be relevant including settings, terminal, and tif properties are included below:
![cellseg_tif_properties](https://user-images.githubusercontent.com/17283036/178798254-cc309067-a19c-41bd-b28a-3dfc3b8a2760.png)

![cellseg_trail_settings](https://user-images.githubusercontent.com/17283036/178798271-86871408-43ab-4b4e-9f78-03c84fc252f2.png)

![cellseg_trail_terminal](https://user-images.githubusercontent.com/17283036/178798282-16db80d9-712a-4037-bb89-4652ef88bc67.png)

**Comment by C-Achard** [comment]
Given the error (and the fact that memory usage is not increasing), this seems to be a reader error, i.e. the chosen reader by MONAI's LoadImaged transform is unable to open your file. The unknown field warnings also point towards this.

Do you know exactly which kind of .tiff file is being created by ImageJ, and are you able to open your file in the napari viewer ?

**Comment by C-Achard** [comment]
If you are able to open your 2D images folder in napari (Using "File > Open Folder"), you can then save the whole as a single 3D .tif file which should work with the plugin (just tested with a folder of 2D .png files)

**Comment by thecobb** [comment]
It's the standard tiff image format in FIJI (screenshot showing option selected below. I'm also able to load the entire file in napari viewer. It's a 3D tiff image.  

![cellseg_fiji_tiff](https://user-images.githubusercontent.com/17283036/178811540-7c3029f1-275d-4ca8-80f4-bf437a3dbccf.png)

![cellseg_napari_viewer](https://user-images.githubusercontent.com/17283036/178812135-37071216-3c6d-4bd5-8e75-9a8d20ab1bca.png)

![cellseg_task_viewer](https://user-images.githubusercontent.com/17283036/178812143-0e8eeb5c-9f35-456d-b05a-1017e1ac2c93.png)

**Comment by thecobb** [comment]
Ok I'll try it using napari to save it.

**Comment by C-Achard** [comment]
Okay, great, let me know if this works

**Comment by thecobb** [comment]
Okay I used Tifffile within Napari to save a subset of my scan as a .tif file (11GB) which worked to resolve the loading error, but now prior to inference starting (during the Monai transforms stage since when I tried using a 44GB .tif file it errored out during this stage saying it couldn't allocate 128GB of RAM which is the total amount on this workstation) performing inference on that 11GB file uses 90-100 GB of RAM which makes using the scan not possible. Additionally, I've tried inference using a window size of 32 and 16 with the VNET for the former and SegResNet with the latter, and both errored out at the inference stage saying it tried to allocate 32GB of VRAM when only 24GB was available - screenshots below). I'm going to try using a smaller window size again and if that doesn't work I will use the keep data on CPU option.

![cellseg_settings](https://user-images.githubusercontent.com/17283036/178854456-905cb1e3-29b6-4a4b-b07f-00233fe0c210.png)
![cellseg_activity_terminal](https://user-images.githubusercontent.com/17283036/178854458-f4237a27-8c9b-41ce-9b58-40f093e64916.png)
![cellseg_activity_Processes](https://user-images.githubusercontent.com/17283036/178854461-9f3cb70a-ced5-463b-880d-bc786e80a7bc.png)
![cellseg_activity_monitor](https://user-images.githubusercontent.com/17283036/178854462-72c91381-7926-4246-873d-d941d9d22f9d.png)

**Comment by C-Achard** [comment]
#### (Concise answer : Maybe try using the "keep data on CPU" option, and reduce the image size.)

Okay, glad that using napari resolved the issue with the reader.

It seems it is errorring at the inference stage now, since you're getting the "Inference started on image n°1" message.
If it were crashing at the MONAI transform stage it wouldn't go past the "Loading dataset" stage, which is where the transforms are used.
So it's most likely running out of memory when it's allocating space for the model itself, not the image. 
An 11Gb image is still extremely large, from our earlier tests on a workstation with fairly similar specs (RTX A4000 + 128 Gb RAM iirc), you might be able to go up to a cube of ~256 - 512 pixels, but not much more. 
3D UNets are very memory-intensive, especially VNet, so it's very easy to run out of memory; do you think you could try on a much smaller volume ? 8192x8192x128 is still an extremely large file for the models we provide, I'm afraid.
Sadly I do not have access to the workstation right now, so I can not give you a more precise estimate of the upper bound for the image size I'm able to load successfully, but if you'd like I can do so later, once I'm able to.

What bothers me more is window inference not reducing the memory requirements, as I thought it would.
As mentioned in this [thread on MONAI's Github page](https://github.com/Project-MONAI/MONAI/discussions/3497), you might get better results if you use the "Keep on CPU" option, as this does exactly what is suggested in the thread (i.e. keep the model on the VRAM and the dataset on the RAM). 
It would still use the VRAM for the model, so it should be faster than running without CUDA, it will simply use the RAM and not the VRAM for the dataset only.

**Comment by thecobb** [comment]
Good news, it ran to completion using a window size of 16 with Vnet and the "keep data on the cpu" option selected as well as the perform thresholding option. The GPU memory usage was low throughout (less than 3 GB of the 21 GB available) but CUDA utilization was constant at 88% for the 4ish hours it says the worker ran to complete inference. I would use the trailmap_MS weights since my guess is that's less memory intensive if that is working but as mentioned in another issue there seems to be a mismatch between the weights loaded and the model. Is the window size selection not cubic? I can make the volume less than 100 planes in the z dimension but I had thought that it needed to be greater than 64 to have a window size selection of 64.

**Comment by C-Achard** [comment]
Great !

Yes, sadly there was an error when the weights were uploaded to the server, I'll contact the admin of the server to try and update those, as I do not have access to it myself.

You are correct about window inference, if you're using a size of 64 on say a 128x128x32 image, it will use 32 and not 64 in the z direction I think. This might lead to errors if the smaller dimension is the image is not a power of two.

**Comment by C-Achard** [comment]
On a side note, were you able to check if the results seem satisfactory ? It'd be very useful to get some feedback on model performance, if you wouldn't mind. No need for thorough benchmarking, just a quick visual check to see if results makes sense.

**Comment by C-Achard** [comment]
Quick update : TRAILMAP_MS is now functional on the #19 PR, if you'd like to try this model right now you can grab the code by cloning the [cy/log_weights_download](https://github.com/AdaptiveMotorControlLab/CellSeg3d/tree/cy/log_weights_download) branch and running `pip install -e .` in the cloned repo folder.

**Comment by thecobb** [comment]
I'll try the TRAILMAP_MS model shortly. I've encountered a different error when running the Instance Segmentation that seems to be driven by the "save stats to csv" option when selected. The error during this step is 
`TypeError: 'ValueError' object is not subscriptable`

and I'm attaching a .txt file with the full terminal output as well as screenshots of terminal output and settings: 

[cellseg_segresnet_terminal_output.txt](https://github.com/AdaptiveMotorControlLab/CellSeg3d/files/9114671/cellseg_segresnet_terminal_output.txt)

![cellseg_terminal_segresnet](https://user-images.githubusercontent.com/17283036/179067281-7d8078b9-5d89-4149-a3ef-0f7961a85ad8.png)

![cellseg_settings_segresnet](https://user-images.githubusercontent.com/17283036/179067247-7a0417cb-d2d3-40e5-993b-72d3827fa7b0.png)

In terms of the predicted output (using the SegResnet), it seems like there's both downsampling (by a factor of 2x) and a transpose that occurs that makes the overlay of the predicted output not match up with the original .tif file. The predicted output has half as many z-steps and needs to be resaved in Napari using the transpose function to have the right orientation. I'm including screenshots of the predictions overlayed with the original image to show both the alignment problem (which may be fixable by upsampling the prediction using interpolation so I will comment if that works) as well as screenshots showing the difference in number of z-planes between the original image and the prediction output. Overall I think the model is doing a decent job I just need to get the predictions properly aligned with the original image. 

Predicted output overlaid on original image in Napari:

![cellseg_results](https://user-images.githubusercontent.com/17283036/179068876-65ac65be-9964-4a80-8865-2591db717134.png)

![cellseg_results2](https://user-images.githubusercontent.com/17283036/179068885-3dad7783-bfea-4e14-b047-79f9f265b30c.png)

Predicted output showing 48 z-steps:

![cellseg_results3_downsampled](https://user-images.githubusercontent.com/17283036/179068921-9184dcdf-41d1-4793-ae00-e529770c606f.png)

Original Image showing 101 z-steps
![cellseg_results3_original_image](https://user-images.githubusercontent.com/17283036/179069436-914eb2fc-606b-4922-8cd8-cfeda6b28929.png)


Lastly there appears to be a type of artifact near the top and bottom of the image seen in the screenshot below. 

![cellseg_results3_ringingArtifact](https://user-images.githubusercontent.com/17283036/179068911-c567e87c-1b55-4f35-b2a3-eb73742c0619.png)

**Comment by thecobb** [comment]
So one issue I'm having comparing the outputs with the originals to see if the predictions are satisfactory is that if I have the compare prediction with original in Napari option selected, it overloads the ram at the display in Napari step. I'll see if I can resolve this starting with seeing if I can get the padding operation from Monai to allow for a 1-1 overlay of the original image stack with the predicted image stack.

**Comment by MMathisLab** [comment]
Let's open a new issue then for this; since the original thread is getting long, and is resolved :) @thecobb feel free to open a new issue for the z-step issue.
