### ISSUE TITLE
Bug - Cannot select Images directory when file format .tiff is selected 

### ISSUE THREAD

**Issue by thecobb** [AdaptiveMotorControlLab/CellSeg3d#21]
The title describes the bug. Right now I can select a directory when the file format in inference is .tif but not .tiff. I'm including a dropbox capture link of a screen capture showing the issue.

[https://capture.dropbox.com/kP1Q4LiwqOGn0dW9](https://capture.dropbox.com/kP1Q4LiwqOGn0dW9)

**Comment by C-Achard** [comment]
Might be related to the reader being unable to read the FIJI/ImageJ processed file (warnings regarding unknown fields) as mentioned in #20
