### ISSUE TITLE
.tif files restricted

### ISSUE THREAD

**Issue by hausmanns** [AdaptiveMotorControlLab/CellSeg3d#56]
1.

https://github.com/AdaptiveMotorControlLab/CellSeg3d/blob/022ebad9e98a5ce14adbc52ecd5c200ec6d9f8d7/napari_cellseg3d/code_plugins/plugin_model_inference.py#L787

Not sure this is the right line of code, but it seems that when I try to run inference on a folder that contains .tiff files, it doesn't accept it as a folder and outputs the folder does not contain any compatible .tif files.

When I manually use a .tiff file and run inference on it, this works fine 

2.
Would be nice if prediction outputs from inference (maybe also for instance seg?) have file names that were used for the prediction in their name? 
What do you think?

So far it's simply `Prediction_1_SwinUNetR_2023_11_15_12_00_20.tif` for instance. It's fine when you run it one time but when you run it on a folder it quickly gets confusing to know which file comes from which original file!

**Comment by C-Achard** [comment]
@hausmanns Both are fixed in #58, please feel free to reopen if you run into any issues with the changes ! Thanks again for testing
