### ISSUE TITLE
no display ?

### ISSUE THREAD

**Issue by Nal44** [AdaptiveMotorControlLab/CellSeg3d#63]
Hi,

I installed the plugin and I have no issues so far, the models runs , but I have no display in Napari ? 
Is it suppose to provide the a new label layer in order to visualize the results and adjust parameters ?

Thanks,
antho

**Comment by Nal44** [comment]
once done I get no display and: 
my images are Tif 8bits ... (Z,X,Y) 

any ideas ? 
thanks
antho


"During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\m197816\AppData\Roaming\Python\Python310\site-packages\napari_cellseg3d\code_models\worker_inference.py", line 957, in inference
    inference_loader = self.load_folder()
  File "C:\Users\m197816\AppData\Roaming\Python\Python310\site-packages\napari_cellseg3d\code_models\worker_inference.py", line 212, in load_folder
    data_check = LoadImaged(keys=["image"], image_only=True)(
  File "C:\Users\m197816\AppData\Roaming\Python\Python310\site-packages\monai\transforms\io\dictionary.py", line 162, in __call__
    data = self._loader(d[key], reader)
  File "C:\Users\m197816\AppData\Roaming\Python\Python310\site-packages\monai\transforms\io\array.py", line 255, in __call__
    img = reader.read(filename)
  File "C:\Users\m197816\AppData\Roaming\Python\Python310\site-packages\monai\data\image_reader.py", line 258, in read
    img_.append(itk.imread(name, **kwargs_))
  File "C:\Users\m197816\AppData\Roaming\Python\Python310\site-packages\itk\support\extras.py", line 1313, in imread
    reader = template_reader_type.New(**kwargs)
  File "C:\Users\m197816\AppData\Roaming\Python\Python310\site-packages\itk\support\template_class.py", line 661, in New
    return self._NewImageReader(
  File "C:\Users\m197816\AppData\Roaming\Python\Python310\site-packages\itk\support\template_class.py", line 191, in _NewImageReader
    ImageType = itk.Image[PixelType, dimension]
  File "C:\Users\m197816\AppData\Roaming\Python\Python310\site-packages\itk\support\template_class.py", line 529, in __getitem__
    raise itk.TemplateTypeError(self, key)
itk.support.extras.TemplateTypeError: itk.Image is not wrapped for input type `itk.RGBPixel[itk.US], int`.

To limit the size of the package, only a limited number of
types are available in ITK Python. To print the supported
types, run the following command in your python environment:

    itk.Image.GetTypes()

Possible solutions:
* If you are an application user:
** Convert your input image into a supported format (see below).
** Contact developer to report the issue.
* If you are an application developer, force input images to be
loaded in a supported pixel type.

    e.g.: instance = itk.Image[itk.RGBPixel[itk.UC], int].New(my_input)

* (Advanced) If you are an application developer, build ITK Python yourself and
turned to `ON` the corresponding CMake option to wrap the pixel type or image
dimension you need. When configuring ITK with CMake, you can set
`ITK_WRAP_${type}` (replace ${type} with appropriate pixel type such as
`double`). If you need to support images with 4 or 5 dimensions, you can add
these dimensions to the list of dimensions in the CMake variable
`ITK_WRAP_IMAGE_DIMS`.

Supported input types:

itk.RGBPixel[itk.UC]
itk.RGBAPixel[itk.UC]
itk.Vector[itk.F,2]
itk.Vector[itk.F,3]
itk.Vector[itk.F,4]
itk.CovariantVector[itk.F,2]
itk.CovariantVector[itk.F,3]
itk.CovariantVector[itk.F,4]
itk.SS
itk.UC
itk.US
itk.F
itk.D
itk.complex[itk.D]
itk.complex[itk.F]
itk.Vector[itk.D,2]
itk.Vector[itk.D,3]
itk.Vector[itk.D,4]
itk.SI
itk.UI
itk.UL
itk.ULL
itk.B
itk.FixedArray[itk.F,2]
itk.FixedArray[itk.D,2]
itk.Offset[2]
itk.SymmetricSecondRankTensor[itk.D,2]
itk.SymmetricSecondRankTensor[itk.F,2]
itk.RGBPixel[itk.UC]
itk.RGBAPixel[itk.UC]
itk.Vector[itk.F,2]
itk.Vector[itk.F,3]
itk.Vector[itk.F,4]
itk.CovariantVector[itk.F,2]
itk.CovariantVector[itk.F,3]
itk.CovariantVector[itk.F,4]
itk.SS
itk.UC
itk.US
itk.F
itk.D
itk.complex[itk.D]
itk.complex[itk.F]
itk.Vector[itk.D,2]
itk.Vector[itk.D,3]
itk.Vector[itk.D,4]
itk.SI
itk.UI
itk.UL
itk.ULL
itk.B
itk.FixedArray[itk.F,3]
itk.FixedArray[itk.D,3]
itk.Offset[3]
itk.SymmetricSecondRankTensor[itk.D,3]
itk.SymmetricSecondRankTensor[itk.F,3]
itk.RGBPixel[itk.UC]
itk.RGBAPixel[itk.UC]
itk.Vector[itk.F,2]
itk.Vector[itk.F,3]
itk.Vector[itk.F,4]
itk.CovariantVector[itk.F,2]
itk.CovariantVector[itk.F,3]
itk.CovariantVector[itk.F,4]
itk.SS
itk.UC
itk.US
itk.F
itk.D
itk.complex[itk.D]
itk.complex[itk.F]
itk.Vector[itk.D,2]
itk.Vector[itk.D,3]
itk.Vector[itk.D,4]
itk.SI
itk.UI
itk.UL
itk.ULL
itk.B
itk.FixedArray[itk.F,4]
itk.FixedArray[itk.D,4]
itk.Offset[4]
itk.SymmetricSecondRankTensor[itk.D,4]
itk.SymmetricSecondRankTensor[itk.F,4]
itk.Vector[itk.F,1]
itk.Vector[itk.F,1]
itk.Vector[itk.D,2]
itk.Vector[itk.D,3]
itk.Vector[itk.D,4]
itk.Vector[itk.F,1]
itk.CovariantVector[itk.D,2]
itk.CovariantVector[itk.D,3]
itk.CovariantVector[itk.D,4]
itk.CovariantVector[itk.D,2]
itk.CovariantVector[itk.D,3]
itk.CovariantVector[itk.D,4]
itk.CovariantVector[itk.D,2]
itk.CovariantVector[itk.D,3]
itk.CovariantVector[itk.D,4]
itk.NormalBandNode[itk.Image[itk.F,2]]
itk.NormalBandNode[itk.Image[itk.D,2]]
itk.NormalBandNode[itk.Image[itk.F,3]]
itk.NormalBandNode[itk.Image[itk.D,3]]
itk.NormalBandNode[itk.Image[itk.F,4]]
itk.NormalBandNode[itk.Image[itk.D,4]]

10:57:35 INFO
Worker finished at 10:57:35
10:57:35 INFO ********************
"

**Comment by Nal44** [comment]
converting the tif file to a numpy array made the trick.
Runnning now :)

**Comment by C-Achard** [comment]
Hello Anthony,

Thanks for opening an issue, and sorry you ran into this problem.

Since the initial problem has been fixed, I will close this issue for now, but please feel free to reopen it or create a new one if you encounter any other problem.

Also happy to help with training models or if you have any other questions; please let me know. 
Hope the models work well for you !

Best,
Cyril

**Comment by Nal44** [comment]
thanks , yes training is next on my list, the pre-trained don't give good results on my images, but I really like the facts that many architectures are available :)  , thanks !
antho
