### ISSUE TITLE
Training model

### ISSUE THREAD

**Issue by GiangTranHU** [AdaptiveMotorControlLab/CellSeg3D#87]
I am new to use CellSeg3D. May I have a question about using it?
Do I need to train the model when applying CellSeg3D to my data or can I directly use the pre-trained model in CellSeg3D?
Thank you very much!

**Comment by C-Achard** [comment]
Hello,

Thanks for trying the plugin ! We do have pretrained models, including the self-supervised WNet3D.

These models were trained on a specific imaging modality however (nuclei in whole-brain data, please see the preprint for a quick view). 

If your data is very similar pretrained models should work fine, however if you have very different data you will have to retrain.

Let me know if you need help with the plugin !

Best,
Cyril

**Comment by GiangTranHU** [comment]
Thank you very much for your comments!

**Comment by GiangTranHU** [comment]
Hi Achard,
May I ask you a few questions about CellSeg3D?
I have tried the plugin, but it seems to be slow in my computer for the sample data provided with the plugin.
May I know how long you need to complete the segmentation using either self-supervised or supervised model? I mean only segmentation, no training.
Another question is about self-supervised model, would you please give me a hint how to do the training with your self-supervised model?
Thank you very much and I am looking forward to hearing from you!

**Comment by C-Achard** [comment]
Hello again @GiangTranHU !

- To run WNet3D on CPU it takes about a minute for me on the c5image.tif file provided in examples.
I don't know how large your data is, but no matter what you will likely want to make sure that PyTorch with CUDA is available and correctly installed on your system. This will greatly speed up everything, if you want to try to train a model this will be pretty much necessary.

You can quickly check if CUDA is working in the napari console by running :
`import torch`
`torch.cuda.is_available()` 

- To train the WNet3D, it really depends on your data, but we do have this ["walkthrough" in the documentation](https://adaptivemotorcontrollab.github.io/CellSeg3D/source/guides/training_wnet.html) that you may find useful.

Please let me know if you need further help !

Best,
Cyril

**Comment by GiangTranHU** [comment]
Hi Cyril,
I am sorry for late response!
Thank you very much for your answer and comments!
I will try to set up GPU on my computer to see if the processing time is improved.
Best,
Giang Tran
