### ISSUE TITLE
Using labels in .csv format for training instead of .tiff

### ISSUE THREAD

**Issue by raeesahhy** [AdaptiveMotorControlLab/CellSeg3D#91]
Hi all, 
I'm trying to use CellSeg3d, however I manually annotated my 3D data in Napari so my segmentations are in .csv format. Is there a way to use .csv labels as training/validation data that I'm missing or could anyone please recommend a pipeline to convert them into TIFF?
Thanks so much!

**Comment by C-Achard** [comment]
Hello @raeesahhayatudin,

Thanks for trying the plugin !

I assume you are talking about the .csv from the Labeling tool. This does not actually contain labels, it merely tracks the labeling of your slices, with a status and time taken per slice in it. This is saved one folder above your labels.

The .tif labels should already be saved whenever you hit "Quicksave", at the location you specified. They should be called *_reviewed.tif. You can also always save the layer manually using Ctrl+S as usual in napari.

In the event that your labels were not saved correctly (hopefully not), it would be very useful to know how you were using the Labeling tool as well, that which step were taken, as well as some minimal data description (shape, dtype) so I can update the docs or fix the underlying issue.

Best,

Cyril
